package com.adilabdullayev.psychology.model.counselor;

import com.adilabdullayev.psychology.model.notes.UserCounselorNote;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.Data;
import com.adilabdullayev.psychology.model.enums.CounselorStatus;

import java.time.LocalDateTime;
import java.util.List;

@Entity
@Data
@Table(name = "counselors", uniqueConstraints = {
        @UniqueConstraint(columnNames = "email"),
        @UniqueConstraint(columnNames = "phone")
})
public class Counselor extends CounselorBase {

    // Notes for the counselor
    @OneToMany(mappedBy = "noteOwner", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference
    private List<UserCounselorNote> counselorNotes;

    // Counselor code - unique identifier
    @Column(name = "counselor_code", unique = true)
    private String counselorCode;

    // Counselor status
    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private CounselorStatus status;

    @Column(name = "is_active")
    private boolean isActive = true;

    // Session count for the counselor
    private Integer sessionCount;

    // Last session date
    private LocalDateTime lastSessionDate;

    // Availability days (e.g., "Monday, Wednesday, Friday")
    private String availableDays;


    // Adding the specialization field
    @ManyToOne
    @JoinColumn(name = "specialization_id")
    private CounselorSpecialization specialization;

    // Getter and Setter methods are automatically generated by Lombok


    public List<UserCounselorNote> getCounselorNotes() {
        return counselorNotes;
    }

    public void setCounselorNotes(List<UserCounselorNote> counselorNotes) {
        this.counselorNotes = counselorNotes;
    }

    public String getCounselorCode() {
        return counselorCode;
    }

    public void setCounselorCode(String counselorCode) {
        this.counselorCode = counselorCode;
    }

    public CounselorStatus getStatus() {
        return status;
    }

    public void setStatus(CounselorStatus status) {
        this.status = status;
    }

    public Integer getSessionCount() {
        return sessionCount;
    }

    public void setSessionCount(Integer sessionCount) {
        this.sessionCount = sessionCount;
    }

    public LocalDateTime getLastSessionDate() {
        return lastSessionDate;
    }

    public void setLastSessionDate(LocalDateTime lastSessionDate) {
        this.lastSessionDate = lastSessionDate;
    }

    public String getAvailableDays() {
        return availableDays;
    }

    public void setAvailableDays(String availableDays) {
        this.availableDays = availableDays;
    }

    public CounselorSpecialization getSpecialization() {
        return specialization;
    }

    public void setSpecialization(CounselorSpecialization specialization) {
        this.specialization = specialization;
    }


}
